
# on your computer, run in this directory
# mkdocs serve

site_name: 'KubeLake - K8S Data Platform workshop'
theme:
  name: material
  logo: img/logo.png
markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/esolutions/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/esolutionstech
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/esolutions.tech/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/esolutions.tech/
    - icon: fontawesome/brands/github
      link: https://github.com/eSolutionsTech
